//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TestServer.localhost {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AllEmployeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddToLogoutLogsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddToLogInOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddToChattingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::TestServer.Properties.Settings.Default.TestServer_localhost_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AllEmployeesCompletedEventHandler AllEmployeesCompleted;
        
        /// <remarks/>
        public event AddToLogoutLogsCompletedEventHandler AddToLogoutLogsCompleted;
        
        /// <remarks/>
        public event AddToLogInCompletedEventHandler AddToLogInCompleted;
        
        /// <remarks/>
        public event AddEmployeeCompletedEventHandler AddEmployeeCompleted;
        
        /// <remarks/>
        public event AddToChattingCompletedEventHandler AddToChattingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllEmployees", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Employee[] AllEmployees() {
            object[] results = this.Invoke("AllEmployees", new object[0]);
            return ((Employee[])(results[0]));
        }
        
        /// <remarks/>
        public void AllEmployeesAsync() {
            this.AllEmployeesAsync(null);
        }
        
        /// <remarks/>
        public void AllEmployeesAsync(object userState) {
            if ((this.AllEmployeesOperationCompleted == null)) {
                this.AllEmployeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllEmployeesOperationCompleted);
            }
            this.InvokeAsync("AllEmployees", new object[0], this.AllEmployeesOperationCompleted, userState);
        }
        
        private void OnAllEmployeesOperationCompleted(object arg) {
            if ((this.AllEmployeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllEmployeesCompleted(this, new AllEmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddToLogoutLogs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddToLogoutLogs(string username) {
            this.Invoke("AddToLogoutLogs", new object[] {
                        username});
        }
        
        /// <remarks/>
        public void AddToLogoutLogsAsync(string username) {
            this.AddToLogoutLogsAsync(username, null);
        }
        
        /// <remarks/>
        public void AddToLogoutLogsAsync(string username, object userState) {
            if ((this.AddToLogoutLogsOperationCompleted == null)) {
                this.AddToLogoutLogsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddToLogoutLogsOperationCompleted);
            }
            this.InvokeAsync("AddToLogoutLogs", new object[] {
                        username}, this.AddToLogoutLogsOperationCompleted, userState);
        }
        
        private void OnAddToLogoutLogsOperationCompleted(object arg) {
            if ((this.AddToLogoutLogsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddToLogoutLogsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddToLogIn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddToLogIn(string username) {
            this.Invoke("AddToLogIn", new object[] {
                        username});
        }
        
        /// <remarks/>
        public void AddToLogInAsync(string username) {
            this.AddToLogInAsync(username, null);
        }
        
        /// <remarks/>
        public void AddToLogInAsync(string username, object userState) {
            if ((this.AddToLogInOperationCompleted == null)) {
                this.AddToLogInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddToLogInOperationCompleted);
            }
            this.InvokeAsync("AddToLogIn", new object[] {
                        username}, this.AddToLogInOperationCompleted, userState);
        }
        
        private void OnAddToLogInOperationCompleted(object arg) {
            if ((this.AddToLogInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddToLogInCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddEmployee(int ssn, string name, string surname, string username, string password, string email, string address) {
            this.Invoke("AddEmployee", new object[] {
                        ssn,
                        name,
                        surname,
                        username,
                        password,
                        email,
                        address});
        }
        
        /// <remarks/>
        public void AddEmployeeAsync(int ssn, string name, string surname, string username, string password, string email, string address) {
            this.AddEmployeeAsync(ssn, name, surname, username, password, email, address, null);
        }
        
        /// <remarks/>
        public void AddEmployeeAsync(int ssn, string name, string surname, string username, string password, string email, string address, object userState) {
            if ((this.AddEmployeeOperationCompleted == null)) {
                this.AddEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEmployeeOperationCompleted);
            }
            this.InvokeAsync("AddEmployee", new object[] {
                        ssn,
                        name,
                        surname,
                        username,
                        password,
                        email,
                        address}, this.AddEmployeeOperationCompleted, userState);
        }
        
        private void OnAddEmployeeOperationCompleted(object arg) {
            if ((this.AddEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEmployeeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddToChatting", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddToChatting(string from, string to, System.DateTime date, string msg, string encrypted, string type) {
            this.Invoke("AddToChatting", new object[] {
                        from,
                        to,
                        date,
                        msg,
                        encrypted,
                        type});
        }
        
        /// <remarks/>
        public void AddToChattingAsync(string from, string to, System.DateTime date, string msg, string encrypted, string type) {
            this.AddToChattingAsync(from, to, date, msg, encrypted, type, null);
        }
        
        /// <remarks/>
        public void AddToChattingAsync(string from, string to, System.DateTime date, string msg, string encrypted, string type, object userState) {
            if ((this.AddToChattingOperationCompleted == null)) {
                this.AddToChattingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddToChattingOperationCompleted);
            }
            this.InvokeAsync("AddToChatting", new object[] {
                        from,
                        to,
                        date,
                        msg,
                        encrypted,
                        type}, this.AddToChattingOperationCompleted, userState);
        }
        
        private void OnAddToChattingOperationCompleted(object arg) {
            if ((this.AddToChattingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddToChattingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employee {
        
        private int sSNField;
        
        private string nameField;
        
        private string surnameField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string emailField;
        
        private string addressField;
        
        /// <remarks/>
        public int SSN {
            get {
                return this.sSNField;
            }
            set {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AllEmployeesCompletedEventHandler(object sender, AllEmployeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employee[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employee[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddToLogoutLogsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddToLogInCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddEmployeeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddToChattingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591